### ISSUE TITLE
EURS incompatible with ERC-20 token standard

### ISSUE THREAD

**Issue by john-light** [STASISNET/STASIS-EURS-token-smart-contract#2]
Aragon developers were investigating an issue that a user had depositing EURS into their Aragon organization's using the Aragon Finance app. It was discovered that the reason for the issue is that the EURS token is not compatible with the ERC-20 token standard that the Finance app relies on to properly process deposit transactions. This despite Statis advertising EURS as an "EIP20 token" on the [EURS website](https://eurs.stasis.net/). The issue is documented in full here:

https://help.aragon.org/article/26-depositing-eurs-in-the-finance-app

**Comment by STASISNET** [comment]
Thanks, it has been fixed in the new contract version.
